### ISSUE TITLE
Import error in utils package

### ISSUE THREAD

**Issue by Oswin06** [dsdanielpark/Gemini-API#1]
from .utils import (
ImportError: cannot import name 'extract_cookies_from_brwoser' from 'gemini.utils'

**Comment by dsdanielpark** [comment]
You're very fast. 

We're reusing some code from the previous [Bard API](https://github.com/dsdanielpark/Gemini-API/) package and adjusting the API interface, so it might be difficult to use right now. We aim to stabilize and implement the features of the Bard API by the end of February. 

We're currently updating cookie values automatically in real-time and checking the frequency of these changes, so please wait a bit longer!

**We'll work hard to meet our goal by the end of February.** 

Also, we're always looking for contributors in the open community. Please proceed with as much work as possible and submit a Pull Request. (Only the first Pull Request will be reviewed and approved based on code contributions.)

**Comment by dsdanielpark** [comment]
[Oswin06](https://github.com/Oswin06)
Please, try to use 1.0.4 or above!

We are currently modifying the package with a focus on extensive code refactoring and future maintainability, so errors may occur. We are also in the process of making adjustments to the returned dictionary for easier access in the future.

We appreciate your understanding. Thank you!!!

```
python uninstall python-gemini-api
```


```
python install python-gemini-api==1.0.4
```
