### ISSUE TITLE
Opening new chat session for every prompts

### ISSUE THREAD

**Issue by mdatiqmazumder** [dsdanielpark/Gemini-API#16]
if i run a prompts it starting a new session..for that i can not ask anythg about previous question

**Comment by dsdanielpark** [comment]
I updated buy usally you can reuse session by declaring Gemini class once.

If you want to fix context, consider this codes. 

Thank you!


### 08. Fix context setting rcid
You can specify a particular response by setting its response candidate id(rcid).

```python
# Generate content for the prompt "Give me some information about the USA."
response1 = GeminiClient.generate_content("Give me some information about the USA.")
# After reviewing the responses, choose the one you prefer and copy its RCID.
GeminiClient.rcid = "rc_xxxx"

# Now, generate content for the next prompt "How long does it take from LA to New York?"
response2 = GeminiClient.generate_content("How long does it take from LA to New York?")

```

### 09. Changing the Selected Response from 0 to n
In Gemini, generate_content returns the first response. This may vary depending on length or sorting. Therefore, you can specify the index of the chosen response from 0 to n as follows. However, if there is only one response, revert it back to 0.

```python
from gemini import GeminiModelOutput
GeminiModelOutput.chosen = 1 # default is 0
response1 = GeminiClient.generate_content("Give me some information about the USA.")


```

### Reusable session object
Gemini class suffices for most cases, but use session objects for special cases.

```python
from gemini import Gemini, HEADERS
import requests
cookies = {} 

session = requests.Session()
session.headers = HEADERS

GeminiClient = Gemini(cookies=cookies) # You can use various args
response = GeminiClient.generate_content("Hello, Gemini. What's the weather like in Seoul today?")
```

**Comment by mdatiqmazumder** [comment]
if use rcid and after set GeminiModelOutput.chosen = 1

**Comment by phamxtien** [comment]
send prompt with rcid it returns:
```
Failed to generate content due to an error: All parsing strategies failed. Try to use `Gemini.send_request(prompt)` to get original payload..
Return reponse without parse. If the issue persists, submit it at https://github.com/dsdanielpark/Gemini-API/issues
'str' object has no attribute 'response_dict'
```

**Comment by dsdanielpark** [comment]
Could you try this code and give me whole error message?
```python
response_text, status= GeminiClient.send_request("How long does it take from LA to New York?")
print(response_text)
```

**Comment by mdatiqmazumder** [comment]
after 

> [phamxtien](https://github.com/phamxtien) Could you try this code and give me whole error message?
> 
> ```python
> response_text, status= GeminiClient.send_request("How long does it take from LA to New York?")
> print(response_text)
> ```

after using rcid and response_text, status= GeminiClient.send_request("How long does it take from LA to New York?")
print(response_text)

[Running] python -u "c:\laragon\www\bard\01.py"
)]}'

38
[["wrb.fr",null,null,null,null,[3]]]
58
[["di",196],["af.httprm",195,"-5178636799681980121",87]]
25
[["e",4,null,null,133]]
