### ISSUE TITLE
Gemini to Gemini Advanced?

### ISSUE THREAD

**Issue by opnoice** [dsdanielpark/Gemini-API#17]
Able to change model from Normal gemini to Advance.

**Comment by dsdanielpark** [comment]
Please check this discussion! https://github.com/dsdanielpark/Gemini-API/discussions/18

**Comment by dsdanielpark** [comment]
https://github.com/dsdanielpark/Gemini-API/tree/main?tab=readme-ov-file#usage

You can try this in the next section, but it may not be effective if your account lacks the necessary permissions. Please experiment and if you encounter any issues, feel free to reopen the issue.
