### ISSUE TITLE
Response None

### ISSUE THREAD

**Issue by QuangDiy** [dsdanielpark/Gemini-API#23]
I have tried multiple times, but the response is still None. I hope you can help me resolve it.
![Screenshot 2024-03-18 140726](https://github.com/dsdanielpark/Gemini-API/assets/95539966/313fa94a-c92b-410e-ad3d-b568844d9b6f)

**Comment by dsdanielpark** [comment]
Try to run this code, and copy  all returned text and give it to me.
```python
response_text, code = GeminiClient.send_request("Hello, Gemini. What's the weather like in Seoul today?"
print(response_text)
```

**Comment by QuangDiy** [comment]
This is my response, hope it helps a little to solve
![Screenshot 2024-03-18 145351](https://github.com/dsdanielpark/Gemini-API/assets/95539966/ef436c9c-6c8d-46ea-b4fc-9afd6fff65dd)

**Comment by dsdanielpark** [comment]
Thank you for the detailed report. I'll combine this with issue #14 for processing.

If you find any solutions or ways to address this, I would appreciate it if you could share them.
