### ISSUE TITLE
Error after using rcid for previous chat session

### ISSUE THREAD

**Issue by mdatiqmazumder** [dsdanielpark/Gemini-API#27]
Failed to generate content due to an error: All parsing strategies failed. Try to use `Gemini.send_request(prompt)` to get original payload..
Return reponse without parse. If the issue persists, submit it at https://github.com/dsdanielpark/Gemini-API/issues
)]}'

**Comment by dsdanielpark** [comment]
I updated [readme session](https://github.com/dsdanielpark/Gemini-API?tab=readme-ov-file#-09-fix-context-setting-rcid).

RCID may not persist. If parsing fails, reset `GeminiClient.rcid` to None.

```python
GeminiClient.rcid = None
```
