### ISSUE TITLE
ImportError: cannot import name 'GeminiClient' from 'gemini'

### ISSUE THREAD

**Issue by gskreddy1981** [dsdanielpark/Gemini-API#6]
from gemini import Gemini
from gemini import GeminiClient

async def main():
    cookies = {
# I setup all the cookies as per the instructions in readme file
    }

    client = GeminiClient(cookies=cookies)
    await client.async_init()

    prompt = "Hello, Gemini. What's the weather like in Seoul today?"
    response = client.generate_content(prompt)
    print(response)

**Comment by dsdanielpark** [comment]
[gskreddy1981](https://github.com/gskreddy1981)
Please, try to use 1.0.4 or above!

We are currently modifying the package with a focus on extensive code refactoring and future maintainability, so errors may occur. We are also in the process of making adjustments to the returned dictionary for easier access in the future.

We appreciate your understanding. Thank you!!!

```
python uninstall python-gemini-api
```


```
python install python-gemini-api==1.0.4
```
